### ISSUE TITLE
An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument.

### ISSUE THREAD

**Issue by ruxyb2004k** [MouseLand/Kilosort#275]
Hi,

I just starting using Kilosort 2.5 and while running the "Spikesort" algorithm, I am getting this error: "An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument". This error occurs for N blocks different that 0.

With Kilosort2 everything was working fine. I already run mexGPUall.m in the kilosort-main/CUDA folder and I also changed the set paths in Matlab to completely ignore the old Kilosort2-master folder. 

Does anyone else also get this error and have an idea what could the the issue?
Thanks!

**Comment by claysmyth** [comment]
I also have this error. #274

**Comment by ruxyb2004k** [comment]
Oh, I thought your error is related to something slightly different, as you posted more lines showing errors. I only get this information from kilosort / matlab.

**Comment by marius10p** [comment]
Can you copy paste the entire output so I can see where the error occurs? Also, please run in debug mode to get the exact line on which this happens.

**Comment by lkatsouri** [comment]
Hi Marius, 

I have the same issue using Kilort 2.0. I have the RTX-2080 and Matlab can engage it. I have analysed data up t please see error below: 

Error using  ' 
An unexpected error occurred trying to launch a kernel. The CUDA error was:
invalid configuration argument

Error in ksFilter (line 19)
dataRAW = dataRAW';

Error in ksGUI/updateDataView (line 869)
                    datAllF = ksFilter(datAll, obj.ops);

Error in ksGUI/updateFileSettings (line 541)
                obj.updateDataView()

Error in ksGUI/selectFileDlg (line 474)
                obj.updateFileSettings();

Error in ksGUI>@(~,~)obj.selectFileDlg (line 179)
                'Callback', @(~,~)obj.selectFileDlg);
 
Error while evaluating UIControl Callback.

Error In GUI: 
' Error saving data for phy! reference to non-existent field 'Wphy'

And here is the gpudevice(1) output: 

>> gpuDevice(1)

ans = 

  CUDADevice with properties:

                      Name: 'GeForce RTX 2080'
                     Index: 1
         ComputeCapability: '7.5'
            SupportsDouble: 1
             DriverVersion: 10.2000
            ToolkitVersion: 10
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 8.5899e+09
           AvailableMemory: 7.7491e+09
       MultiprocessorCount: 46
              ClockRateKHz: 1710000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

**Comment by JannaAarse** [comment]
Hey, 

I have the same issue, I change the files in my main_kilosort like they are mentioned in #288 , unfortunately now I get the following error:
Error using gpuArray/hTimesTranspose
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of rows in the second matrix. To perform elementwise multiplication, use '.*'.

Error in shift_batch_on_disk2 (line 37)
dati = gpuArray(single(dat)) * gpuArray(M)';

Error in datashift2 (line 136)
        dprev = shift_batch_on_disk2(rez, ibatch, dshift(ibatch, :), yblk, sig, dprev);

Error in main_kilosort (line 39)
rez = datashift2(rez, 1); % last input is for shifting data

can you help me with the issue  ? I don't know how to go on from here. 

Best, 
Janna

**Comment by RobertoDF** [comment]
Hi! Did you change only main_kilosort? I thnk it would be easier to just clone everything from here https://github.com/RobertoDF/Kilosort/tree/solve_zero_padding

**Comment by JannaAarse** [comment]
Hey ,

thanks , I did this yesterday evening (cloning the whole thing) and did run
it overnight and it works. Thank you so much.

Best,
Janna

On Wed, Dec 30, 2020 at 9:46 AM Roberto DF <notifications@github.com> wrote:

> Hi! Did you change only main_kilosort? I thnk it would be easier to just
> clone everything from here
> https://github.com/RobertoDF/Kilosort/tree/solve_zero_padding
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_RobertoDF_Kilosort_tree_solve-5Fzero-5Fpadding&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=NX0_gz81_KoklNb5kxPgHg&m=ZSdWMkpfq8eq8kj-6mVYV3HZOLMl8YsFe2nXTzOF068&s=ztp2lCUp-aXdKl1PRfZxGK_9wNLw2dP1RqLmuPpL5NI&e=>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MouseLand_Kilosort_issues_275-23issuecomment-2D752646353&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=NX0_gz81_KoklNb5kxPgHg&m=ZSdWMkpfq8eq8kj-6mVYV3HZOLMl8YsFe2nXTzOF068&s=BMlusUxepEMplUFWl9WNcV5kA5DKBXiDakW2m5Cfjj0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMWFGYFB3M47Y2B36EFTIM3SXM4MLANCNFSM4TQOEOSA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=NX0_gz81_KoklNb5kxPgHg&m=ZSdWMkpfq8eq8kj-6mVYV3HZOLMl8YsFe2nXTzOF068&s=8uYAQEkQVYKYuPmgGEzpGbWGpoBz_JnPkGJsERdOU8s&e=>
> .
>


-- 
Janna Aarse, PhD
Center for Neural Science
Angelaki Lab

Meyer Hall,
2-4 Washington Place
New York, 10003
Phone: 212-998-3906

**Comment by RobertoDF** [comment]
That's great! glad to hear it works for others too.
